"""S2.1: the three-filter Samuelson check on the registered ABMI levels (D-021). A check, not a result.

Closed until G2 has passed and the registered ABMI file has been acquired.
Writes audit/s2_verification.json and audit/S2_TABLE.md.
"""
import importlib.metadata
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))
from uc_core import h1_official, samuelson  # noqa: E402


def table(rows):
    lines = ['# S2: the Samuelson reading, a check and not a result', '',
             'Generated by `tools/build_s2.py` from the registered ABMI levels, 1955Q1-2019Q4 (D-021). '
             'An intercept-inclusive AR(2) is fitted to each cycle of 100 ln Y; c = phi1 + phi2 and v = -phi2/(phi1 + phi2); '
             'the reading oscillates when c > 0 and c(1 + v)^2 < 4v. The answer moves with the filter; that sensitivity is the point. '
             'This is standard teaching material (QuantEcon, Samuelson multiplier-accelerator), reported as a check.', '',
             '| Filter | Cycle observations | phi1 | phi2 | Modulus | Period (quarters) | c | v | Oscillates |',
             '|---|---|---|---|---|---|---|---|---|']
    fmt = lambda value, digits: '-' if value is None else f'{value:.{digits}f}'
    for row in rows:
        lines.append(f"| {row['filter']} | {row['cycle_observations']} | {fmt(row['phi1'], 3)} | {fmt(row['phi2'], 3)} | "
                     f"{fmt(row['modulus'], 3)} | {fmt(row['period_quarters'], 1)} | {fmt(row['c'], 3)} | {fmt(row['v'], 3)} | "
                     f"{'-' if row['oscillates'] is None else ('yes' if row['oscillates'] else 'no')} |")
    return '\n'.join(lines) + '\n'


def main():
    h1_official.check_g2(ROOT)
    record, labels, levels = h1_official.load_registered_levels(ROOT)
    rows = samuelson.s2_rows(levels)
    output = dict(record_type='S2 three-filter Samuelson check', label='a check, not a result', decision='D-021',
                  raw_sha256=record['sha256'], sample=[labels[0], labels[-1]], rows=rows,
                  environment=dict(statsmodels=importlib.metadata.version('statsmodels'),
                                   numpy=importlib.metadata.version('numpy')))
    (ROOT / 'audit/s2_verification.json').write_text(json.dumps(output, indent=2) + '\n', encoding='utf-8', newline='\n')
    (ROOT / 'audit/S2_TABLE.md').write_text(table(rows), encoding='utf-8', newline='\n')
    print('audit/S2_TABLE.md written; a check, not a result')


if __name__ == '__main__':
    main()
