"""Render the S1.3 table with S1.4 bands from audit/s1_verification.json into audit/S1_TABLE.md."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RECORD = ROOT / 'audit/s1_verification.json'
OUTPUT = ROOT / 'audit/S1_TABLE.md'
METHOD = {'ols': 'LS', 'yw': 'YW'}


def number(value, digits):
    return '-' if value is None else f'{value:.{digits}f}'


def main():
    record = json.loads(RECORD.read_text(encoding='utf-8'))
    lines = ['# S1 fits and bootstrap bands', '',
             'Generated by `tools/s1_table.py` from `s1_verification.json`; do not edit by hand. '
             'Periods and half-lives are in years. Bands are 95% percentile intervals from 4,000 residual-bootstrap draws (D-018); '
             'period bands use complex-root draws only.', '',
             '| Version | Sample | n | Method | phi1 | phi2 | Modulus | Period | Half-life | Modulus band | Period band | Real-root draws |',
             '|---|---|---|---|---|---|---|---|---|---|---|---|']
    for fit, boot in zip(record['fits'], record['bootstrap']['summaries']):
        modulus_band, period_band = boot['modulus_band'], boot['period_band']
        lines.append('| {} | {} | {} | {} | {} | {} | {} | {} | {} | {}-{} | {}-{} | {} |'.format(
            fit['version'], fit['sample'], fit['n'], METHOD[fit['method']],
            number(fit['phi1'], 3), number(fit['phi2'], 3), number(fit['modulus'], 3),
            number(fit['period'], 2), number(fit['half_life'], 2),
            number(modulus_band[0], 3), number(modulus_band[1], 3),
            number(period_band[0], 2), number(period_band[1], 2), boot['real']))
    lines += ['', '## Version 2 minus Version 1, 1749-1924', '',
              '| Method | phi1 | phi2 | Modulus | Period | Half-life |', '|---|---|---|---|---|---|']
    for row in record['version_differences']:
        lines.append('| {} | {:+.4f} | {:+.4f} | {:+.4f} | {:+.3f} | {:+.3f} |'.format(
            METHOD[row['method']], row['phi1_V2_minus_V1'], row['phi2_V2_minus_V1'],
            row['modulus_V2_minus_V1'], row['period_V2_minus_V1'], row['half_life_V2_minus_V1']))
    comparison = record['statsmodels_vs_silso_v1']
    at13 = record['AT13']
    lines += ['', '## Checks', '',
              f"- Rescaling: least squares on Version 1 divided by 0.6 changes the coefficients by at most "
              f"{record['rescaling_check']['max_coefficient_difference']:.1e}; the median Version 2 / Version 1 ratio over 1749-1924 is "
              f"{record['rescaling_check']['median_ratio_V2_to_V1']:.4f}.",
              f"- The statsmodels yearly series differs from SILSO's frozen Version 1 file in {comparison['years_differing']} of "
              f"{comparison['years_compared']} years ({comparison['years_differing_1749_1924']} within 1749-1924), by at most "
              f"{comparison['max_absolute_difference']:.1f}.",
              f"- AT-13: {'passed' if at13['passed'] else 'failed'}. Period band {at13['bootstrap']['period_band'][0]:.2f}-"
              f"{at13['bootstrap']['period_band'][1]:.2f} years, modulus band {at13['bootstrap']['modulus_band'][0]:.3f}-"
              f"{at13['bootstrap']['modulus_band'][1]:.3f}, {at13['bootstrap']['complex']} of {at13['bootstrap']['B']} draws complex; "
              f"long-series recovery z = {at13['long_series']['z'][0]:+.2f}, {at13['long_series']['z'][1]:+.2f}.", '']
    OUTPUT.write_text('\n'.join(lines), encoding='utf-8', newline='\n')
    print(OUTPUT.relative_to(ROOT))


if __name__ == '__main__':
    main()
